/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsTkpRouteImport } from './routes/analytics/tkp'
import { Route as AnalyticsEkantipurRouteImport } from './routes/analytics/ekantipur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsTkpRoute = AnalyticsTkpRouteImport.update({
  id: '/analytics/tkp',
  path: '/analytics/tkp',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsEkantipurRoute = AnalyticsEkantipurRouteImport.update({
  id: '/analytics/ekantipur',
  path: '/analytics/ekantipur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics/ekantipur': typeof AnalyticsEkantipurRoute
  '/analytics/tkp': typeof AnalyticsTkpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics/ekantipur': typeof AnalyticsEkantipurRoute
  '/analytics/tkp': typeof AnalyticsTkpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics/ekantipur': typeof AnalyticsEkantipurRoute
  '/analytics/tkp': typeof AnalyticsTkpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics/ekantipur' | '/analytics/tkp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics/ekantipur' | '/analytics/tkp'
  id: '__root__' | '/' | '/analytics/ekantipur' | '/analytics/tkp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsEkantipurRoute: typeof AnalyticsEkantipurRoute
  AnalyticsTkpRoute: typeof AnalyticsTkpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/tkp': {
      id: '/analytics/tkp'
      path: '/analytics/tkp'
      fullPath: '/analytics/tkp'
      preLoaderRoute: typeof AnalyticsTkpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/ekantipur': {
      id: '/analytics/ekantipur'
      path: '/analytics/ekantipur'
      fullPath: '/analytics/ekantipur'
      preLoaderRoute: typeof AnalyticsEkantipurRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsEkantipurRoute: AnalyticsEkantipurRoute,
  AnalyticsTkpRoute: AnalyticsTkpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
